%% Basic Simulink Model Template
% Auto-generated by Claude Simulink Skill
% Usage: out = basic_model('myModel')

function out = basic_model(modelName)
    arguments
        modelName (1,1) string
    end

    % Cleanup existing model
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end

    % Create and open model
    new_system(modelName);
    open_system(modelName);

    % === ADD BLOCKS ===
    add_block("simulink/Sources/Sine Wave", modelName + "/Sine Wave", ...
        "Position", [100 100 150 130], ...
        "Amplitude", "1", ...
        "Frequency", "2*pi");

    add_block("simulink/Math Operations/Gain", modelName + "/Gain", ...
        "Position", [250 100 290 130], ...
        "Gain", "2");

    add_block("simulink/Sinks/Scope", modelName + "/Scope", ...
        "Position", [400 100 440 130]);

    add_block("simulink/Sinks/To Workspace", modelName + "/ToWorkspace", ...
        "Position", [400 180 460 210], ...
        "VariableName", "simout", ...
        "SaveFormat", "Dataset");

    % === CONNECT BLOCKS ===
    add_line(modelName, "Sine Wave/1", "Gain/1", "autorouting", "smart");
    add_line(modelName, "Gain/1", "Scope/1", "autorouting", "smart");
    add_line(modelName, "Gain/1", "ToWorkspace/1", "autorouting", "smart");

    % === CONFIGURE SIMULATION ===
    set_param(modelName, "StopTime", "10");
    set_param(modelName, "Solver", "ode45");

    % === RUN SIMULATION ===
    out = sim(modelName);

    % === REPORT RESULTS ===
    simData = out.simout;
    fprintf("=== SIMULATION COMPLETE ===\n");
    fprintf("Model: %s\n", modelName);
    fprintf("Stop Time: 10s\n");
    fprintf("Output variable: simout\n");
    fprintf("Dataset elements: %d\n", simData.numElements);
    fprintf("=== END ===\n");

    % === SAVE ===
    save_system(modelName);
end
