%% Feedback Control System Template
% Auto-generated by Claude Simulink Skill
% Usage: out = feedback_control('myControlModel')

function out = feedback_control(modelName)
    arguments
        modelName (1,1) string
    end

    % Cleanup existing model
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end

    % Create and open model
    new_system(modelName);
    open_system(modelName);

    % === ADD BLOCKS ===
    % Reference input (Step)
    add_block("simulink/Sources/Step", modelName + "/Reference", ...
        "Position", [50 100 80 130], ...
        "Time", "1", "After", "1");

    % Sum junction (error = ref - feedback)
    add_block("simulink/Math Operations/Sum", modelName + "/Sum", ...
        "Position", [150 100 170 120], ...
        "Inputs", "+-");

    % Controller (Gain = Kp)
    add_block("simulink/Math Operations/Gain", modelName + "/Controller", ...
        "Position", [230 100 270 130], ...
        "Gain", "10");

    % Plant: Transfer function G(s) = 1/(s+1)
    add_block("simulink/Continuous/Transfer Fcn", modelName + "/Plant", ...
        "Position", [340 100 400 130], ...
        "Numerator", "[1]", ...
        "Denominator", "[1 1]");

    % Output scope
    add_block("simulink/Sinks/Scope", modelName + "/Scope", ...
        "Position", [500 100 540 130]);

    % To Workspace for result extraction
    add_block("simulink/Sinks/To Workspace", modelName + "/ToWorkspace", ...
        "Position", [500 180 560 210], ...
        "VariableName", "yout", ...
        "SaveFormat", "Dataset");

    % === CONNECT BLOCKS ===
    % Forward path
    add_line(modelName, "Reference/1", "Sum/1", "autorouting", "smart");
    add_line(modelName, "Sum/1", "Controller/1", "autorouting", "smart");
    add_line(modelName, "Controller/1", "Plant/1", "autorouting", "smart");
    add_line(modelName, "Plant/1", "Scope/1", "autorouting", "smart");
    add_line(modelName, "Plant/1", "ToWorkspace/1", "autorouting", "smart");

    % Feedback path
    add_line(modelName, "Plant/1", "Sum/2", "autorouting", "smart");

    % === CONFIGURE & ARRANGE ===
    set_param(modelName, "StopTime", "10");
    set_param(modelName, "Solver", "ode45");
    Simulink.BlockDiagram.arrangeSystem(modelName);

    % === RUN ===
    out = sim(modelName);

    % === REPORT ===
    fprintf("=== SIMULATION COMPLETE ===\n");
    fprintf("Model: %s\n", modelName);
    fprintf("Controller: P (Kp=10)\n");
    fprintf("Plant: 1/(s+1)\n");
    fprintf("=== END ===\n");

    % === SAVE ===
    save_system(modelName);
end
